variables:
  GO111MODULE: "on"

stages:
  - "test"

run-tests:
  stage: "test"
  image: "golang:1.12-alpine"
  cache:
    key: "gomodules"
    paths:
      - "/go/pkg/mod"
  script:
    - "apk add --no-cache git ca-certificates"
    - "go test ./..."
