variables:
  GO111MODULE: "on"

stages:
  - "test"

run-tests:
  stage: "test"
  image: "golang:latest"
  cache:
    key: "gomodules"
    paths:
      - "/go/pkg/mod"
  script:
    - "go test -v ./..."
