variables:
  GO111MODULE: "on"

image: docker:stable

services:
  - docker:dind

stages:
  - "test"
  - "build"

run-tests:
  stage: "test"
  image: "golang:latest"
  cache:
    key: "gopath"
    paths:
      - ".gopath"
  script:
    - "mkdir -p .gopath"
    - "export GOPATH=$CI_PROJECT_DIR/.gopath"
    - "go test -v ./..."

build-image:
  stage: "build"
  script:
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com"
    - "docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:latest ."
    - "docker push $CI_REGISTRY_IMAGE:latest"
